package rs.edu.raf.storage;

public enum Operations {
    FILTER_EXTENSION, FILTER_FILENAME, SORT_BY_NAME_ASC, SORT_BY_NAME_DESC, SORT_BY_DATE_CREATED, SORT_BY_DATE_MODIFIED_ASC, SORT_BY_DATE_MODIFIED_DESC
}
